services:
  # Account Service #
  account:
    container_name: account
    build: ../backends/account-back
    volumes:
      - ../backends/account-back/src:/app
      - ../backends/shared:/app/shared
    env_file:
      - ../backends/account-back/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - accountpg
      - accountredis
    restart: unless-stopped
  accountpg:
    container_name: accountpg
    image: postgres:17.6-alpine3.22
    volumes:
      - account_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backends/account-back/.env.example
    ports:
      - "5432:5432"
    restart: unless-stopped
  accountredis:
    container_name: accountredis
    image: redis:7.4.5-alpine
    volumes:
      - account_redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
  accountmongo:
    image: mongo:7.0.25-jammy
    container_name: accountmongo
    env_file:
      - ../backends/account-back/.env.example
    ports:
      - "27017:27017"
    volumes:
      - account_mongodb_data:/data/db

  # Chat Service #
  chat:
    container_name: chat
    build: ../backends/chat-back
    volumes:
      - ../backends/chat-back/src:/app
      - ../backends/shared:/app/shared
    env_file:
      - ../backends/chat-back/.env.example
    ports:
      - "8001:8000"
    depends_on:
      - chatpg
      - chatredis
    restart: unless-stopped
  chatpg:
    container_name: chatpg
    image: postgres:17.6-alpine3.22
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backends/chat-back/.env.example
    ports:
      - "5433:5432"
    restart: unless-stopped
  chatredis:
    container_name: chatredis
    image: redis:7.4.5-alpine
    volumes:
      - chat_redis_data:/data
    ports:
      - "6378:6379"
    restart: unless-stopped
  chatmongo:
    image: mongo:7.0.25-jammy
    container_name: chatmongo
    env_file:
      - ../backends/chat-back/.env.example
    ports:
      - "27018:27017"
    volumes:
      - chat_mongodb_data:/data/db

volumes:
  account_postgres_data:
    driver: local
  account_redis_data:
    driver: local
  account_mongodb_data:
    driver: local
  chat_postgres_data:
    driver: local
  chat_redis_data:
    driver: local
  chat_mongodb_data:
    driver: local
